### ISSUE TITLE
Required support

### ISSUE THREAD

**Issue by Ritooon** [pitininja/select-mania#1]
It would be great if the required attribute would be supported 🐶

**Comment by pitininja** [comment]
Currently the original select element is hidden with a `display:none` rule.

Here is a fix to implement so the native `required` attribute is supported:

First the original select element must be moved inside the select-mania container.

Then hide the original select element with these rules:
`border: 0 !important;
clip: rect(0 0 0 0) !important;
height: 100% !important;
margin: 0! important;
overflow: hidden! important;
padding: 0! important;
position: absolute !important;
width: 100% !important;`

Make sure the select-mania container has `position:relative`

**Comment by pitininja** [comment]
The `required` attribute is now supported! \o/
