### ISSUE TITLE
Add some keyboard gestures

### ISSUE THREAD

**Issue by Ritooon** [pitininja/select-mania#3]
1) When using "tab" between inputs, "tab" doesn't trigger the select-mania dropdown

2) Would be great to allow the possibility to choose options in the dropdown with keyboard arrows 

3) Would be great to allow the selection with "Enter" keyboard key (Combo with point 2)

Cheers 🍻

**Comment by pitininja** [comment]
Keyboard controls now supported on v1.1 (pre-release).
