### ISSUE TITLE
Select-mania and select disabled

### ISSUE THREAD

**Issue by Ritooon** [pitininja/select-mania#5]
Select-mania ignores "disabled" attribute of the select initialized with it.

Example of disabled normal select which is not with _select-mania_  : 
`<select id="leSelect" class="selectMania" disabled="disabled"><option value="1">Value 1</option><option value="2">Value 2</option></select>`

**Comment by pitininja** [comment]
Disabled attribute is not currently supported on the select element. Added this feature to the roadmap.

**Comment by pitininja** [comment]
Disabled attribute is now supported on v1.1 (pre-release).
