### ISSUE TITLE
How to populate the correct initialization

### ISSUE THREAD

**Issue by MaPoLom** [pitininja/select-mania#7]
See previous issue

"There is no "double initialization", this is the normal behaviour: the original select element is given a new class select-mania-original (in order to hide it), and the visible select-mania element is built with the select-mania class and more styling classes like the tiny one."

The problem is this. When populating the select-box dynamic in a script upon page load the hidden first initialized class "select-mania-original" gets populated and not the "Tiny" one.

Is there a way to copy the content from the "original" to "Tiny" after population or rather to fill the right class. 

The loop that I'm using does this by 'getElementById' and I think because the HTML gives the class the Element name it gets automatically copied.

Kind regards

Maurice

**Comment by pitininja** [comment]
I feel like you're trying to insert options in the original select dynamically, and update the select-mania element accordingly, right?

After inserting options in the original select element, you can call the `update` method to reflect changes to the built element.

Hope it helps, if not, can you provide some code and example?

**Comment by MaPoLom** [comment]
I would be happy to provide some code but this is a pieve of software which can't be found online. Can you reach out to me on a pivate line? (email)

**Comment by pitininja** [comment]
Ok let's do this! 👌

**Comment by MaPoLom** [comment]
To give some insights: Here is the webdev view which hows only the original on gets filled. Even after the update the tiny is still empty.

![image](https://user-images.githubusercontent.com/11076201/33667180-78977d8a-da9c-11e7-82a1-6bc738525773.png)

**Comment by pitininja** [comment]
I just emailed you on your hotmail address ;)

**Comment by MaPoLom** [comment]
And it's in your mail box! Thank you!
