### ISSUE TITLE
Initial display setting

### ISSUE THREAD

**Issue by Ritooon** [pitininja/select-mania#8]
It would be great to let the possibility to change the display of the select-mania (Like display:none) at initialization in the settings

**Comment by pitininja** [comment]
Hey!

You can now use a `hidden` setting set to true (or a `data-hidden="true"` attribute) so select-mania initialize hidden.

There's also two new methods: `hide` and 'show` that manipulate select-mania display.

These features are available in the v1.4 release.

Enjoy :)
