### ISSUE TITLE
It doesn't show the placeholder.

### ISSUE THREAD

**Issue by juniorbatistaRD** [pitininja/select-mania#9]
I pass the placeholder through the attribute data-placeholder but it is not working

**Comment by pitininja** [comment]
Can you please provide an example of your code so I can help?

**Comment by pitininja** [comment]
Please take a look at [this fiddle](https://jsfiddle.net/uahymsbf/3/) where I use the `data-placeholder` attribute. Of course, in order to see the Placeholder at initialization, you must not have any value selected. The `empty` setting can be used to initialized the select with an empty value.
